apiVersion: v1
name: query-me
description: Simple web app that returns the ip address of the requesting client or the list of ip adressess that have queried the app in the past.
type: application
version: 0.1.0
appVersion: "v1"
